# config.yaml
seed: 20
arch: "custom"
epochs: 10
dataset: "cifar10"
batch_size: 32
learning_rate: !!float 0.001
num_workers: 2
pre_trained: false
freeze_backbone: false
use_amp: true
use_weight_decay: !!float 5e-4 # force float
use_scheduler: !!float 1e-6 # minimal learning rate for scheduler
use_grad_clip: !!float 1.0
data_dir: "./data"
artifacts_dir: "./artifacts"